### ISSUE TITLE
The ingo_library dependency is really bad

### ISSUE THREAD

**Issue by ayuanx** [inkarkat/vim-mark#10]
Just for a few trivial MSG and ERR that nobody cares, we have to install a library containing at least 100 files, and 99.9% of them are not used by 99.9% of people.
This is just bad practice.

**Comment by ayuanx** [comment]
I end up deleting all pointless "ingo#err" and "ingo#msg" to keep my vim lean, fast and clean. Sigh.

**Comment by ayuanx** [comment]
Anyway, I made a standalone version that does not depend on any library.
https://github.com/ayuanx/vim-mark-standalone

**Comment by inkarkat** [comment]
<sup>I'd call commenting about issues in an derogatory tone a bad practice, especially because you don't seem to fully understand the issue.</sup>

Separating common functions is explicitly recommended by Vim; see `:help write-library-script`:

> Some functionality will be required in several places.  When this becomes more
> than a few lines you will want to put it in one script and use it from many
> scripts.  We will call that one script a library script.

The autoload mechanism was created to make this really easy and efficient. Only those scripts that contain functions that are actually used are loaded, the rest is ignored; it just "wastes" the space on disk. (At currently 800 KB / 4.2 MB with Git history, that should today be negligible.) If you really have a problem with Vim not being fast or clean, you need to look elsewhere.

If you only use my Mark plugin, yes, this might look wasteful. But keep in mind that I'm not the original author of this particular plugin, so it doesn't utilize the full potential of reuse yet. (However, my next planned feature for Mark will introduce more use of the ingo-library.) I have published 120+ more plugins (most of which now use ingo-library). Considering that, the decision to extract the common functionality (which caused a lot of effort for me) benefits both users (no duplication, no incompatibilities, faster updates) and me (less overall effort in maintaining, more time for features).

Finally, other plugin authors have done the same (see [here](https://github.com/inkarkat/vim-ingo-library#related-works)).

---

In the end, this is open source, and you're free to do what you want. If you don't want the dependency and want to spend the effort to pull in the functions, fine. You seem to have "cloned" the code by copying the sources; if you had used GitHub's _fork_ functionality instead, your fork would be linked and easily discoverable by other users through GitHub's network feature. I think it would also make it easier to pull in any future changes happening my side.

**Comment by ayuanx** [comment]
My point is that vim always needs to read and parse every single line in the bloated library.
One of my favorite parts of vim over emacs is that vim boots in less than 0.01 second, and I am determined to keep it so.
Because I run and close vim hundreds of times per day using it more like a "scribbler".
But thank you for replying any way.

**Comment by pacak** [comment]
FWIW I wasted some time trying to understand why plugin works but throws errors.
