### ISSUE TITLE
Suppress "mapping already exists"

### ISSUE THREAD

**Issue by last5bits** [inkarkat/vim-mark#11]
I have mappings that vim-mark attempts to redefine, so at each vim startup, I get:

```
Error detected while processing /home/a84089393/.vim/bundle/vim-mark/plugin/mark.vim:
line  163:
E227: mapping already exists for  n
```

How can I suppress the warnings? Thanks in advance and a separate thank you for this great plugin.

**Comment by inkarkat** [comment]
This error is caused by the `<unique>`. I don't usually put that in my plugins; any existing mapping would then be silently overwritten. But the original Mark plugin had it like that, and there are both pros and cons for each approach. If you have a strong opinion here, I'd like to hear it!

---

How to solve this depends on what exactly you finally want:

#### Keep the existing mapping, want to use different keys for this Mark mapping:

Just define your own mapping, e.g.

    nmap ,,n <Plug>MarkClear

This must be done _before_ Mark is loaded; usually in your `~/.vimrc`.

#### Keep the existing mapping, I don't want this Mark mapping at all:

Define a dummy mapping to a `<Plug>Disable...` key combo that will _never_ trigger:

    nmap <Plug>DisableMarkClear <Plug>MarkClear

If the other plugin does not use `<unique>` in its definition, you could also switch the order of sourcing the plugins (so that Mark comes first), but that's overly complex and not very clear.

#### Override the existing mapping with Mark's default:

If the other mapping also uses this canonical `<Plug>`-mapping approach, you can use one of the above. Some plugins may use `g:...` variables to disable mappings. Worst case, you have to edit that plugin and comment out / change the mapping directly in the script.

<sup>That's a general plugin configuration problem, by the way; nothing special about Mark here.</sup>

**Comment by voldikss** [comment]
> #### Keep the existing mapping, want to use different keys for this Mark mapping:
> Just define your own mapping, e.g.
>```
>nmap ,,n <Plug>MarkClear
>```
@inkarkat 
Just remind that 
`map` is better than `nmap` here, because some original mapping are `xmap`, see this line:
https://github.com/inkarkat/vim-mark/blob/f3686933214d5f4da6c773bd448841ffe8dbe5a5/plugin/mark.vim#L248
