### ISSUE TITLE
Conflict with Jedi

### ISSUE THREAD

**Issue by emprovements** [inkarkat/vim-mark#12]
Hi,
Great plugin! But i just found out that key mapping has conflict with vim-jedi plugin. Would it be possible to have remapping options via "let" ?

**Comment by VoldikSS** [comment]
@emprovements 
The author has used `unique` method to pre-bind some keys. I have to say it is troublesome to solve the conflicts with other plugins @inkarkat :neckbeard: 
You unbind these keys by re-mapping these keys with some meaningless strings. Here are examples:
```vim
" unbind <Leader>*
nmap <Plug>DisableMarkSearchCurrentNext <Plug>MarkSearchCurrentNext
" unbind <Leader>r
nmap <Plug>DisableMarkRegex <Plug>MarkRegex
" unbind <Leader>n
nmap <Plug>DisableMarkClear <Plug>MarkClear
" unbind <Leader>/
nmap <Plug>DisableMarkSearchAnyNext <Plug>MarkSearchAnyNext
" unbind <Leader>?
nmap <Plug>DisableMarkSearchAnyPrev <Plug>MarkSearchAnyPrev
" unbind *
nmap <Plug>DisableMarkSearchNext <Plug>MarkSearchNext
" unbind #
nmap <Plug>DisableMarkSearchPrev <Plug>MarkSearchPrev
```
After unbinding, you can re-bind those to whatever you want.

**Comment by emprovements** [comment]
Thank you a lot for enlightenment ;-)

**Comment by inkarkat** [comment]
As @VoldikSS has commented, you can disable any default mappings that are not wanted or in conflict. If you just want to reassign a different mapping, there's no need to unbind and re-bind; just define your mapping to the `<Plug>`-mappings _before_ the plugin runs, e.g. in your `~/.vimrc`.

By the way, this is the canonical way to handle custom mappings; your suggested alternative via `:let` config variables is rather unusual (and only warranted if there are many mappings with a common prefix, or other peculiarities).

I personally don't like the default mappings at all, and have remapped almost everything. I'm reluctant to change the defaults, though, because that would probably affect most plugin users. (And I haven't yet received any feedback that the default mappings are particularly bad, so it may be just me.)
