### ISSUE TITLE
Can't copy marked word?

### ISSUE THREAD

**Issue by skelliam** [inkarkat/vim-mark#26]
Hi Ingo, thank you for maintaining this plugin.  Looking at the docs I can't seem to find a solution for this.  If I mark a word by double-clicking it, it is not 'selected' in Vim, and therefore I cannot CTRL-C (in Windows) to copy this word to the clipboard anymore.  So basically, if I double-click a word, it gets highlighted (good), but then I have to manually drag my mouse over it to "select" it for copy (bad).  Is there a workaround for this that I'm missing? 

Thank you!

**Comment by inkarkat** [comment]
Hi William,

I'm have trouble seeing the link to my plugin, as it doesn't modify Vim's default double-click behavior. When you double-click a word, Vim will create a selection (visual or select mode), as described by [`:help double-click`](https://vimhelp.appspot.com/term.txt.html#double-click).

Based on your description, your problem seems to be the discrepancy between Vim's own selection and what the terminal itself uses. With a native Vim on Windows and the Windows Console (or with GVIM), this shouldn't be a problem. That behavior is controlled by the [`'mouse'`](https://vimhelp.appspot.com/options.txt.html#%27mouse%27) option, though. You'll hopefully find some additional information elsewhere; the solution depends a lot on your particular setup and terminal emulator.

Happy Vimming!
