### ISSUE TITLE
Cannot search github.com for this plugin because it is forked

### ISSUE THREAD

**Issue by fedorenchik** [inkarkat/vim-mark#35]
**Describe the bug**

Due to how github search algorithm works, it's impossible to search for this plugin by it's name, that is: `vim-mark`.

This happens because this repo is forked from other one.

**How to Reproduce**

Search `vim-mark` from github.com front page, observe there are no results for `vim-mark`, even many pages down.

But less popular & less maintained scripts, that are not forks, will be shown.

I think this is serious issue in popularity of this plugin.

**Expected Behavior**

Remove `forked from vim-scripts/Mark` from this repo (make it not a fork somehow (maybe contact github.com stuff or recreate repo (in the long term, it will be beneficial still))).

**Environment**
 - github.com

**Comment by inkarkat** [comment]
It's indeed hard to find _vim-mark_. However, I think it is also partially due to the abundance of _markdown_ Vim plugins, so the original repo also isn't very high in the list :-(

When looking at the [network graph](https://github.com/vim-scripts/Mark/network/members), at least it is pretty clear that my fork is _the_ most popular one.

I'm not sure what fiddling with the fork status will bring. There are various sites around Vim plugins (e.g. https://vimawesome.com/ (where the markdown plugins also drown out this plugin)), and the original _vim.org_ plugin registry. So, there should be lots of ways to find my plugin. This isn't about popularity, anyway; too much popularity just means less work to spend on those plugins originally authored by me :-)
