### ISSUE TITLE
[Unrelated to the plugin] Help creating an anonymizer plugin

### ISSUE THREAD

**Issue by MasterMedo** [inkarkat/vim-mark#37]
Hi there,

I was hoping we could discuss an unrelated idea for a plugin I want to create, but I'm unsure which method would be the fastest and if it would be possible to accomplish in vim without much lag.

I want to create a buffer anonymizer. Something similar to *mzggg?G`z*, except instead of doing a ROT13 on the text it would convert all characters to squares. Basically, I want to achieve something similar to:

![image](https://user-images.githubusercontent.com/16375100/123219638-67cffc00-d4cd-11eb-9a66-a60586ecfa52.png)

The problem is, I want to keep the current highlighting group of every character in the buffer after I swap each character for a square. Do you have an idea how might I go about doing that?

**EDIT**: I found a better image

**Comment by inkarkat** [comment]
Oh, that's an interesting problem.

Fastest and easiest surely would be switching the [`'guifont'`](https://vimhelp.appspot.com/options.txt.html#%27guifont%27) to a custom one where each glyph would be that square. Of course, the downside is that this only works in GVIM, and it requires a system-specific font installation outside of Vim. (Which quite some users have already done, however, for a nicer statusline provided by plugins like _vim-airline_ - I think the plugin even automates that part.)

---

If you replace every character with an `X` (or Unicode █ (U+2588)), syntax-highlighting would break (and you'd have to handle undo).

---

The [`:syn-conceal`](https://vimhelp.appspot.com/syntax.txt.html#%3Asyn-conceal) feature is of no use because everything affected is highlighted by the single `Conceal` group.

---

However, you can "hide" each character by making its foreground and background colors identical; only the character the cursor is on might still be revealed. This would effectively be a _colorscheme_ modification; you could edit the colorscheme manually, making all `fg` = `bg`, or even do this programmatically:

    function! hi#Conceal() abort
        for l:hlGroupName in filter(getcompletion('.*', 'highlight'), 'v:val != "Normal"')
            let l:synId = synIDtrans(hlID(l:hlGroupName))
            let l:fg = synIDattr(l:synId, 'fg')
            let l:bg = synIDattr(l:synId, 'bg')
            let l:color = (empty(l:fg) ? (empty(l:bg) ? 'black' : l:bg) : l:fg)
            let l:command = printf('hi %s guibg=%s guifg=%s', l:hlGroupName, l:color, l:color)
            execute l:command
        endfor
    endfunction
    command! -bar HiConceal call hi#Conceal()

The only problem here is plain text that is not highlighted at all. As this uses the [`hl-Normal`](https://vimhelp.appspot.com/syntax.txt.html#hl-Normal) group which also affects the background where there's no text at all, you won't get a block highlighting for those; **that text will remain or at best vanish into the background** (if you set `Normal`'s fg := bg).

Unfortunately, it's not so easy to match all text that's not yet highlighted. Something like

    :syn match otherText "\S\+"

would eclipse the existing syntax rules.

So I think you'd have to go throug the entire [visible] text, extract those non-whitespace characters not highlighted (using [`synID()`](https://vimhelp.appspot.com/eval.txt.html#synID%28%29)), and then define matches for them - preferably using [`matchadd()`](https://vimhelp.appspot.com/eval.txt.html#matchadd%28%29), not via `:syntax`, to avoid interfering with the existing syntax. Of course, then you also have to deal with the fact that `matchadd()` is window-scoped; _vim-mark_ has the same challenge, and you can reuse the same concepts from it (like using [`win_execute()`](https://vimhelp.appspot.com/eval.txt.html#win_execute%28%29) to update all visible windows).

That's potentially a lot of text covered by the matches; I'm not sure how well Vim would deal with it. If this scales well, you might forgo the entire colorscheme modification and define the highlighted parts in the same way:

    :hi red guibg=red guifg=red
    ...
    :call matchadd('red', '\%1l\%1v.')
    ...

---

In closing, there unfortunately is no easy way to achieve this, but it's also not impossible. I also already had the idea of hiding passwords in a text by using the _conceal_ feature, but that would only be few instances and I wouldn't mind that the highlighting changes.

I wouldn't recommend this project for a beginner in Vim customization (though you'd likely learn a lot...) If you decide to do this and publish a plugin, feel free to post a link to it here. Good luck, and happy Vimming!

**Comment by MasterMedo** [comment]
Thanks for taking the time to write all this. This is exactly the kind of message I was hoping for! I don't have a lot of experience with customization plugins. So far I created a couple of colour schemes, a language syntax highlighting file for Cypher, custom folding functions and something similar to [Sayonara](mhinz/vim-sayonara).
The password concealer sounds kinda cool, not sure what's the use case though.

I intend to use nerdfonts, of course!

The colour scheme trick is pretty neat. But unfortunately it wouldn't satisfy me. I need the gaps between lines to achieve this effect.

My initial idea was:
1. use [scriptease](https://github.com/tpope/vim-scriptease) to somehow get the highlighting groups of each character
2. save the row and column of each character
3. transform each character in the buffer appropriately to square or pattern ending e.g.
```vim
function! s:lencompare(a, b) abort
```
would turn into 4 blobs, as adjacent words coloured the same would melt into one blob, like so:
```
(====red===)(=purple=)(blue) (red)
```

From a theoretical point of view, this should be pretty easy, and most importantly **fun**, to do.
I'll dive into this idea a bit further over the next week.
If I fail with vanilla vimscript I'll try lua. I've been using neovim for the past 2 years after all, it's about time I get my hands dirty...

**Comment by inkarkat** [comment]
You don't need _scriptease_ to extract the syntax / highlighting; this is basically just [`synID()`](https://vimhelp.appspot.com/eval.txt.html#synID%28%29). [SyntaxAttr.vim - Show syntax highlighting attributes of character under cursor](https://github.com/inkarkat/SyntaxAttr.vim) also does something like that, too.

Finding runs of characters that have the same highlighting indeed is an interesting problem. I've done something similar in my [SameSyntaxMotion plugin](https://github.com/inkarkat/vim-SameSyntaxMotion). But there, it's just for a single jump, not parsing the whole [visible] buffer at once, so performance is less of an issue.

The idea of my password concealer is that the sensitive parts are not shown (or at least those not on the current line - which can be controlled via conceal options), but can still be copied to the clipboard - to avoid shoulder surfers getting a glimpse at my password database.

**Comment by MasterMedo** [comment]
I completely forgot about shoulder surfers... This quarantine has lasted for a while now!
The password concealer is useful in a public workspace for sure, especially if you use vim as a password manager (:no_judging_emoji:).

After drawing a diagram and some python pseudocode it was pretty easy to write a proof of concept script.
I even came close to doing it with vimscript, but as soon as I came to the realization vimscript doesn't have a `continue` keyword for loops, meaning I'd have to have a million if-else blocks indented at least 16 spaces to the right I gave up on it. I remembered there's a python module, and since I already had the code in python I figured why not start there.

First results:
![image](https://user-images.githubusercontent.com/16375100/123416330-b60cfa00-d5b6-11eb-82bd-0624840ecb5f.png)
![image](https://user-images.githubusercontent.com/16375100/123417979-c6be6f80-d5b8-11eb-83f5-ccb1f71bae99.png)

Currently I have a problem with `hl-Normal` as you can see. I'll have to figure out how to increase the priority of highlighting (although that won't be the issue if using obscure characters), in this scenario they are coloured green because there's a preceding `#` which is a comment in python.

The thing I'm really worried about is many edge cases:
1. characters that take more than 1 space
2. multiple highlight groups (this is probably not an issue since `synID` returns the group with the highest priority?)
3. manually doing match delete (currently I'm using nvim's `add_highlight` to avoid this)
4. multiple windows, floating windows, airline, ...

I'm thinking maybe a better direction would be instead of creating a vim plugin, create a terminal "plugin"? Then you can anonymize anything that's going on. Plus, that should be pretty easy to do in some terminals if there's an API for those sorts of things. Then you'd be able to literally conceal the view of the user and have the full functionality of programs in terminal as if they weren't concealed. But this would work only on emulators I suppose. I'm using `st` so I'd have to check if that's possible.

**Comment by inkarkat** [comment]
Oh, that's looking promising already!

Attacking this in the terminal certainly have some benefits, surely a much wider applicability. I'm not sure when (and how long) you'd actually use this anonymization. I imagine it could be helpful for short demos or screencasts, where the actual contents are not important (or even distracting). And for the terminal, just switching to a special font might be all that is needed.

PS: Surely Vimscript has [`:continue`](https://vimhelp.appspot.com/eval.txt.html#%3Acontinue); some aspects of the language are explicitly modeled after Python.
