### ISSUE TITLE
Tiny Suggestion: Make clearer that one needs to install dependency vim-ingo-library

### ISSUE THREAD

**Issue by dienluong** [inkarkat/vim-mark#43]
**Motivation**

Thank you so much for this plug-in!  I used to use an obscur editor on Windows called emeditor because it lets you multi-highlight words.  Now that I switched to Linux, I was desperate to find something that does the same.  Couldn't find an editor with this feature built-in.  I suspected Vim community must have made some customization that allows this.  I'm so glad I find your plug-in!

I'm relatively new to Vim, especially the plug-ins side.  It was not totally obvious to me how to install the plug-in.

**Request and Purpose**

Just add a small mention in the README that plug-in vim-ingo-library must be installed as well,  The plug-in is mentioned in the dependencies section but it might not be clear enough to some that one has to explicitly install it and exactly where to find it.

I realize this requirement only after I got errors when trying to mark a word.  Then, I went through the README again carefully making sure I didn't miss anything. I did read the dependencies before but assumed that it was already included with the plug-in. Then, I checked my local cloned vim-mark repo (downloaded by vim-plug) to verify if there was anything ressembling that dependency.  Nothing. That's when I started to suspect I had to explicitly install it.

**Alternatives**

_A clear and concise description of any alternative solutions or features you've considered._

**Comment by inkarkat** [comment]
Thanks for the feedback, and welcome to Vim; it's indeed a bit special and occasionally "weird" due to its heritage, but well worth learning!

I'm aware of the problems of plugin dependencies; unfortunately, though some plugin managers already allow to model and automatically handle dependencies, this is still an uphill battle, and far from solved. With over 100 plugins published, not having dependencies would not be feasible for me, neither.

Therefore, I try to clearly document the dependency (and the [docs](https://github.com/inkarkat/vim-mark/blob/89274036663c3322c669ff499a128583018604d3/README.md#L329-L330) state _Requires the ingo-library.vim plugin_) - this plugin's documentation is very long, so it's easy to overlook. My second line of defense is the custom GitHub issue template, that [explicitly addresses failures due to the ingo-library missing](https://github.com/inkarkat/vim-mark/blob/cb355630cea195816df656c0652c9d873bcbb48b/.github/ISSUE_TEMPLATE/bug_report.md#L10). That has greatly reduced the amount of emails and issues for me, but yes, it still isn't optimal, and I hope that sometime in the future plugin managers will solve this once and for all.

Happy Vimming!
